import { Footer } from '@/src/components/Footer/Footer'
import { Navigation } from '@/src/components/Navigation/Navigation'
import { playfair, raleway } from '@/src/styles/fonts'
import '@/src/styles/scss/globals.scss'

export const metadata = {
  title: 'Fromagerie des Cimes - Avoriaz',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="fr">
      <body className={`${playfair.variable} ${raleway.variable}`}>
        <Navigation />
        {children}
        <Footer />
      </body>
    </html>
  )
}
