import { Geist, Geist_Mono } from "next/font/google";
import { Footer } from "@/src/components/Footer/Footer";
import {playfair, raleway } from "@/src/styles/fonts"
import '@/src/styles/scss/globals.scss';



export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="fr">
      <body className={`${playfair.variable} ${raleway.variable}`}>
        {children}
        <Footer />
      </body>
    </html>
  );
}
